---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $NAME_SERVICE
spec:
  selector:
    matchLabels:
      app: $NAME_SERVICE
  replicas: 1
  template:
    metadata:
      labels:
        app: $NAME_SERVICE
    spec:
      containers:
        - name: $NAME_SERVICE
          image: $IMAGE
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 1500m
            requests:
              cpu: 500m

--- 

kind: Service
apiVersion: v1
metadata:
  name: $NAME_SERVICE
spec:
  type: LoadBalancer
  selector:
    app: $NAME_SERVICE
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: $NAME_SERVICE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $NAME_SERVICE
  minReplicas: 1  
  maxReplicas: 5  
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50












